"""baseline mvp schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-15 00:10:06.928291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cover_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key_configs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('encrypted_key', sa.TEXT(), nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('word_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_chapters_project_id', ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('content_text', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parse_threshold', sa.VARCHAR(length=10), nullable=False),
    sa.Column('require_manual_confirm', sa.BOOLEAN(), nullable=False),
    sa.Column('imported_at', sa.VARCHAR(length=30), nullable=False),
    sa.Column('parse_result_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_project_id', ['project_id'], unique=False)

    op.create_table('knowledge_cards',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('card_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_json', sqlite.JSON(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('source_doc_ids', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_cards_project_id', ['project_id'], unique=False)

    op.create_table('project_settings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('auto_parse_confirm', sa.BOOLEAN(), nullable=False),
    sa.Column('default_temperature', sa.FLOAT(), nullable=False),
    sa.Column('default_max_tokens', sa.INTEGER(), nullable=False),
    sa.Column('default_view', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('chapter_knowledge_cards',
    sa.Column('chapter_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('card_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id', 'card_id')
    )
    op.create_table('generation_records',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('chapter_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('generation_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('input_text', sa.TEXT(), nullable=True),
    sa.Column('params_json', sqlite.JSON(), nullable=False),
    sa.Column('output_candidates', sqlite.JSON(), nullable=False),
    sa.Column('selected_output', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_records', schema=None) as batch_op:
        batch_op.create_index('ix_generation_records_chapter_id', ['chapter_id'], unique=False)
        batch_op.create_index('ix_generation_records_project_id', ['project_id'], unique=False)

    op.create_table('knowledge_snippets',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('card_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('start_offset', sa.INTEGER(), nullable=True),
    sa.Column('end_offset', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_snippets', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_snippets_card_id', ['card_id'], unique=False)
        batch_op.create_index('ix_knowledge_snippets_document_id', ['document_id'], unique=False)
        batch_op.create_index('ix_knowledge_snippets_project_id', ['project_id'], unique=False)

    op.create_table('version_snapshots',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('chapter_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_version_snapshots_chapter_id', ['chapter_id'], unique=False)

    op.create_table('generation_card_links',
    sa.Column('generation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('card_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_id'], ['generation_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('generation_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_card_links')
    with op.batch_alter_table('version_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_version_snapshots_chapter_id')

    op.drop_table('version_snapshots')
    with op.batch_alter_table('knowledge_snippets', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_snippets_project_id')
        batch_op.drop_index('ix_knowledge_snippets_document_id')
        batch_op.drop_index('ix_knowledge_snippets_card_id')

    op.drop_table('knowledge_snippets')
    with op.batch_alter_table('generation_records', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_records_project_id')
        batch_op.drop_index('ix_generation_records_chapter_id')

    op.drop_table('generation_records')
    op.drop_table('chapter_knowledge_cards')
    op.drop_table('project_settings')
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_cards_project_id')

    op.drop_table('knowledge_cards')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_project_id')

    op.drop_table('documents')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_chapters_project_id')
        batch_op.drop_index('ix_chapters_parent_id')

    op.drop_table('chapters')
    op.drop_table('api_key_configs')
    op.drop_table('projects')
    op.drop_table('app_configs')
    # ### end Alembic commands ###
